# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('courses', multiselectfield.db.fields.MultiSelectField(choices=[('py', 'Python'), ('dj', 'Djang'), ('ui', 'UI'), ('ra', 'Rest Api')], max_length=200)),
                ('branches', multiselectfield.db.fields.MultiSelectField(choices=[('hyd', 'Hyderabad'), ('bang', 'Bangalore'), ('che', 'Chennai'), ('pune', 'Pune')], max_length=200)),
                ('gender', models.CharField(max_length=50)),
                ('startdate', models.DateField(max_length=50)),
            ],
        ),
    ]
